version: '3.8'

services:
  viterbit-mcp:
    build: .
    container_name: viterbit-mcp-server
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - VITERBIT_API_KEY=${VITERBIT_API_KEY}
      - MCP_API_KEYS=${MCP_API_KEYS}
      - PORT=8000
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
