[project]
name = "mcp-viterbit"
version = "0.1.0"
description = "Claude MCP server for Kämpe Viterbit integration"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
requires-python = ">=3.10"

[tool.uv]
